{"name": "test_login2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <script.test_login.TestLogin object at 0x0000000003943438>\n\n    def test_login2(self):\n>       assert 0\nE       assert 0\n\nscript\\test_login.py:7: AssertionError"}, "start": 1601950147130, "stop": 1601950147130, "uuid": "debab583-76a6-4d9d-8151-a1ed7e12897b", "historyId": "7e4333e82bdc7efa6e4fef87baffb865", "testCaseId": "f90a1b98e56ad7f8d745a3321c3be890", "fullName": "script.test_login.TestLogin#test_login2", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "SKY-20171211NJY"}, {"name": "thread", "value": "6424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_login"}]}